# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34121ccc59dfa1788fe32311d09d145d5803491c9230accc0b45367723054a4e75415b81730a9fa430565aad46bade1b07b09a4ba20020cf46a7e12272e452a9

test:
  secret_key_base: 3cbfd3a9bfba62d5cd7f44b420d51759200e3ded97f78ac4de8fcacd5e2e64ea24ad75aaff573278e9a7fd8716ac71bd1ec7a98f05f4bf19152a675f6bab724f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
